### ISSUE TITLE
While logged in, other people's characters appear as if they're editable, but aren't

### ISSUE THREAD

**Issue by KatrinaKitten** [blakewatson/minimal-character-sheet#10]
When opening a character sheet owned by a different account while actively logged in, the sheet appears as if it's editable, and changes can be made to the data on the sheet. Upon refreshing, the sheet returns to its original state, so it doesn't appear that this actually updates the database, making it relatively harmless, but it is a bit of an odd difference compared to viewing while not logged in, which disables all of the fields.

**Comment by blakewatson** [comment]
@KatrinaKitten Your totally right! Thanks for catching that. I just deployed a fix for it.

Closed by 00e93000f51a2d136e36cf9e4fcbdf445e27f7ef
