### ISSUE TITLE
Can't delete characters

### ISSUE THREAD

**Issue by KatrinaKitten** [blakewatson/minimal-character-sheet#8]
Once a character has been created, the Delete button on the sheet does not appear to function, and they cannot be removed from the list of created characters. Their sheet continues to function normally, but unwanted sheets end up clogging the list.

**Comment by blakewatson** [comment]
@KatrinaKitten Thanks for reporting this. I'll look into it. It’s possible I broke that functionality as part of a recent-ish update to make optionally public character sheets.

**Comment by blakewatson** [comment]
@KatrinaKitten I’ve deployed a fix for this! Closed by 44d24c697ca93308343cde2015a1f25a134a5de1.
